### ISSUE TITLE
Emails Template Set Up

### ISSUE THREAD

**Issue by sxngie** [sxngie/Rewwardy#53]
Using [mailchimp ](https://mailchimp.com/), develop a template and edit it to match Rewwardy and its branding.

- [x] Sign Up (Client & Admin) [this will inform the user the account has been created.]
- [x] Reward received [notifies user that they have completed the progress towards a reward]
- [x] Forgot password (Client & Admin)

Main Colors:
- White (#FFFFFF)
- Purple (#463489)

Accent Colors:
- Pink (#F72585)
- Dark Pink (#9B2C6B)

**Comment by christianrosado20** [comment]
Sign Up Email Template



![Image](https://github.com/sxngie/Rewwardy/assets/31023073/35d88380-05c9-4b40-b5ee-bb93baaf443c)

**Comment by christianrosado20** [comment]
Puedes utilizar el mismo template y le cambias el contenido para cada task

**Comment by emiliodejesus** [comment]
Published the email_notifications branch with each of these email templates. Took this beyond and completed a working password reset for both admin and regular users. Got started and made a file for the initial setup of node mailer in order to use this templates to send emails, still on progress.
