### ISSUE TITLE
Account and Application Testing Phase 1

### ISSUE THREAD

**Issue by sxngie** [sxngie/Rewwardy#54]
Do the following tasks and identify any bugs with the functionality and processing. 

_Remember logging in is required to navigate through the application._

- [x] Create 5 business accounts (Admin)
- [x] Create 2 rewards 
- [x] Validate the rewards are visible for the admin in the View All Rewards page
- [x] Create 5 accounts (Users)
- [x] Navigate the application as a user
- [x] Validate the rewards are visible for users

**Comment by emiliodejesus** [comment]
Awaiting bug fixes to the functionality of the app in order to resume testing. Account creation is working smoothly.

**Comment by emiliodejesus** [comment]
Application has been updated and many changes has been applied. @sxngie has conducted multiple test including but not limited to Reward redeem, scan counts, challenge selection and progress, reward creation and tested challenge progress as well as admin side tests!
